// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiTUw9ba7gzasXd5E2URkDmNWOe4SXktY',
    appId: '1:165045154073:web:83301382d3853ba502d588',
    messagingSenderId: '165045154073',
    projectId: 'doctorappointmentapp-8229d',
    authDomain: 'doctorappointmentapp-8229d.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-8229d.firebasestorage.app',
    measurementId: 'G-W8GXVSM9ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv5jXNp81Mh2qLTsQEYBnUvxFjJI6Buhk',
    appId: '1:165045154073:android:24f5df6f62c766c502d588',
    messagingSenderId: '165045154073',
    projectId: 'doctorappointmentapp-8229d',
    storageBucket: 'doctorappointmentapp-8229d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-82U03UjqbMlTiHnr9BxGrF2Y2UKpO2w',
    appId: '1:165045154073:ios:78e342af5128ae1a02d588',
    messagingSenderId: '165045154073',
    projectId: 'doctorappointmentapp-8229d',
    storageBucket: 'doctorappointmentapp-8229d.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppointmentDr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-82U03UjqbMlTiHnr9BxGrF2Y2UKpO2w',
    appId: '1:165045154073:ios:78e342af5128ae1a02d588',
    messagingSenderId: '165045154073',
    projectId: 'doctorappointmentapp-8229d',
    storageBucket: 'doctorappointmentapp-8229d.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppointmentDr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiTUw9ba7gzasXd5E2URkDmNWOe4SXktY',
    appId: '1:165045154073:web:11e824488a61119802d588',
    messagingSenderId: '165045154073',
    projectId: 'doctorappointmentapp-8229d',
    authDomain: 'doctorappointmentapp-8229d.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-8229d.firebasestorage.app',
    measurementId: 'G-T320CL7L5B',
  );
}
